/*
  Minimal consumer permissions for the two Retail Dashboard views.

  The role that OWNS the views must retain access to their underlying objects.
  RETAIL_DASHBOARD_READ_ROLE does not need access to those underlying objects.
*/

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RETAIL_DASHBOARD_READ_ROLE
  COMMENT = 'Read-only consumer of the Retail Business Dashboard views';

GRANT USAGE ON WAREHOUSE SALES_WH
TO ROLE RETAIL_DASHBOARD_READ_ROLE;

GRANT USAGE ON DATABASE DATA_MART
TO ROLE RETAIL_DASHBOARD_READ_ROLE;

GRANT USAGE ON SCHEMA DATA_MART.RETAIL_DASHBOARD
TO ROLE RETAIL_DASHBOARD_READ_ROLE;

GRANT SELECT ON VIEW DATA_MART.RETAIL_DASHBOARD.WEEKLY_RETAIL_ACTUALS
TO ROLE RETAIL_DASHBOARD_READ_ROLE;

GRANT SELECT ON VIEW DATA_MART.RETAIL_DASHBOARD.MARKETING_SPEND_YTD
TO ROLE RETAIL_DASHBOARD_READ_ROLE;

GRANT ROLE RETAIL_DASHBOARD_READ_ROLE TO ROLE SYSADMIN;

-- Assign after the service/read-only user exists:
-- GRANT ROLE RETAIL_DASHBOARD_READ_ROLE TO USER <RETAIL_DASHBOARD_USER>;

SHOW GRANTS TO ROLE RETAIL_DASHBOARD_READ_ROLE;
